# Generated by Django 4.2.3 on 2023-08-13 12:20

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_alter_blog_blog_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='rich',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
