# Generated by Django 4.2.3 on 2023-08-13 12:34

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_blog_rich'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='rich',
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
